name: release version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven
      - uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "rdc-releases",
                "username": "${secrets.MVN_USERNAME}",
                "password": "${secrets.MVN_PASSWORD}"
              }
            ]
          profiles: >
            [
              {
                "id": "rdc",
                "properties": {
                  "altReleaseDeploymentRepository": "rdc-releases::default::https://packages.aliyun.com/maven/repository/2040008-release-fvpoDf/"
                }
              }
            ]
          active_profiles: >
            [
              "rdc"
            ]
          output_file: .m2/settings.xml
      - name: Build with Maven
        run:  cat /home/runner/work/practice/practice/.m2/settings.xml
