name: release version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: |
          echo $DAY_OF_WEEK
          mvn --batch-mode --update-snapshots package -Dmaven.test.skip=true
