name: release version
on:
  push:
    branches:
      - master
env:
  GITHUB_YYY: ${{ secrets.YYY }}
  GITHUB_ZZZ: ${{ secrets.ZZZ }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run:  echo x ${{ GITHUB_XXX }} y ${{ GITHUB_YYY }} z ${{ GITHUB_ZZZ }}
