name: release version
on:
  workflow_dispatch:
    inputs: 
      CI_COMMIT_TAG:
        description: 'for release semantic versioning'
        required: true 
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven
      - uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: >
            [{
                "id": "rdc-releases",
                "username": "${{ secrets.MVN_USERNAME }}",
                "password": "${{ secrets.MVN_PASSWORD }}"
            }]
          profiles: >
            [{
                "id": "rdc",
                "properties": {"altReleaseDeploymentRepository": "rdc-releases::default::https://packages.aliyun.com/maven/repository/2040008-release-fvpoDf/"}
            }]
          active_profiles: >
            ["rdc"]
          output_file: /home/runner/.m2/settings.xml
      - name: Build Release
        run: |
          git checkout -B for_release
          mvn versions:set-property -DgenerateBackupPoms=false  -Dproperty=revision -DnewVersion=${{ inputs.CI_COMMIT_TAG }} 
          mvn clean install -U -Dmaven.test.skip=true --batch-mode -s /home/runner/.m2/settings.xml
          git config --global user.email "ci-bot@corant.org"
          git config --global user.name  "ci-bot"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -a -m "ci release ${{ inputs.CI_COMMIT_TAG }} "
          git tag ${{ inputs.CI_COMMIT_TAG }} 
          git push origin ${{ inputs.CI_COMMIT_TAG }} 
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "hello"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      # - name: Post to a Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
      #     channel-id: 'cicd'
      #     # For posting a simple plain text message
      #     slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #   env:
      #     SLACK_BOT_TOKEN: xoxb-737952375093-1472149530068-e8XW464m06ZbigAATMegZxmp
      
      # - name: Slack notification
      #   env:
      #     SLACK_WEBHOOK: https://hooks.slack.com/services/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
      #     # SLACK_USERNAME: ThisIsMyUsername # Optional. (defaults to webhook app)
      #     # SLACK_CHANNEL: general # Optional. (defaults to webhook)
      #     # SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      #   uses: Ilshidur/action-slack@2.1.0
      #   with:
      #     args: 'test'
